# fly.toml app configuration file generated for move-green on 2023-04-22T01:16:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "move-green"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443